name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

  workflow_dispatch:

jobs:
  build-dist:
    runs-on: ubuntu-latest
    name: Build dist
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Build dist files
        run: |
          python setup.py sdist bdist_wheel
      - name: Save dist files
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  publish-pypi:
    runs-on: ubuntu-latest
    name: Publish to PyPI
    environment: publish-pypi
    permissions:
      id-token: write
    needs:
      - build-dist
    steps:
      - name: Get dist files
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      - name: Publish dist files
        uses: pypa/gh-action-pypi-publish@release/v1
